// <auto-generated />
using Cadastro_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroAPI.Migrations
{
    [DbContext(typeof(SistemaCadastrosDBContext))]
    [Migration("20221229010243_relacionamentos")]
    partial class relacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cadastro_API.Models.CadastroModel", b =>
                {
                    b.Property<int>("cadastro_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cadastro_Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("data_nascimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("cadastro_Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("Cadastro_API.Models.TelefonesModel", b =>
                {
                    b.Property<int>("telefone_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("telefone_Id"));

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.Property<int>("cadastroID")
                        .HasColumnType("int");

                    b.HasKey("telefone_Id");

                    b.HasIndex("cadastroID");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Cadastro_API.Models.TelefonesModel", b =>
                {
                    b.HasOne("Cadastro_API.Models.CadastroModel", "cadastro")
                        .WithMany("telefones")
                        .HasForeignKey("cadastroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cadastro");
                });

            modelBuilder.Entity("Cadastro_API.Models.CadastroModel", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
